import { SocietyPost } from "@/types";

export const societyPosts: SocietyPost[] = [
  {
    id: "island-code",
    slug: "the-island-code",
    title: "THE ISLAND CODE",
    excerpt: "Three rules. Don't pollute. Don't litter. Don't mess with Poros. This is the code we live by and the code we print on our backs. If you wear it, you carry it.",
    tag: "manifesto",
    date: "2026-04-20",
    pinned: true,
  },
  {
    id: "beach-cleanup",
    slug: "poros-beach-cleanup-may",
    title: "BEACH CLEANUP — ASKELI, MAY 10",
    excerpt: "We're organizing a cleanup on Askeli beach. Show up at 9AM. Bring gloves. Wear your BEPOROS. If you love the island, prove it.",
    tag: "event",
    date: "2026-05-10",
  },
  {
    id: "summer-popup",
    slug: "summer-popup-harbor",
    title: "SUMMER POP-UP ON THE HARBOR",
    excerpt: "One night. Limited pieces. Music. The harbor. Date TBA — follow @beporos for the signal.",
    tag: "event",
    date: "2026-06-01",
  },
  {
    id: "summer-26",
    slug: "summer-26-lineup",
    title: "SUMMER '26 — WHAT'S COMING",
    excerpt: "New artifacts in the works. A collaboration with a local artist. And something we've never done before. Stay locked.",
    tag: "announcement",
    date: "2026-04-18",
  },
  {
    id: "1963-story",
    slug: "why-1963",
    title: "WHY 1963?",
    excerpt: "The year that shaped the island. Before the tourists, before the marina — when Poros was just Poros. The story behind the design.",
    tag: "culture",
    date: "2026-04-10",
  },
  {
    id: "locals-spotlight",
    slug: "locals-spotlight-kapetan-yiannis",
    title: "LOCALS: KAPETAN YIANNIS",
    excerpt: "40 years on the water. He's seen every sunrise from the strait. We sat with him and listened.",
    tag: "culture",
    date: "2026-04-05",
  },
  {
    id: "first-drop-recap",
    slug: "drop-001-sold-out",
    title: "DROP 001 — CLAIMED IN 48HRS",
    excerpt: "The first transmission hit different. Both artifacts gone in two days. If you got one, you're part of the foundation.",
    tag: "news",
    date: "2026-03-28",
  },
  {
    id: "water-quality",
    slug: "poros-water-quality-report",
    title: "POROS WATER QUALITY — 2026 REPORT",
    excerpt: "We pulled the latest data on the island's swimming waters. The results are mostly good — but there's one bay that needs attention.",
    tag: "news",
    date: "2026-03-20",
  },
];