import { SocietyPost } from "@/types";

export const societyPosts: SocietyPost[] = [
  {
    id: "summer-2-announce",
    slug: "summer-2-is-coming",
    title: "SUMMER 2 IS COMING",
    excerpt: "2 new tees. 100 units each. Drop date announced soon on IG. If you missed Summer 1, don't sleep on this one.",
    tag: "announcement",
    date: "2026-04-20",
    pinned: true,
  },
  {
    id: "beach-cleanup",
    slug: "askeli-beach-cleanup",
    title: "BEACH CLEANUP — ASKELI, MAY 10",
    excerpt: "9AM at Askeli. Bring gloves. We clean the beach, then we swim. Show up.",
    tag: "event",
    date: "2026-05-10",
  },
  {
    id: "popup-summer",
    slug: "summer-popup",
    title: "POP-UP ON THE HARBOR — JUNE TBA",
    excerpt: "One night. Both tees. Music. The harbor. Follow @beporos for the exact date.",
    tag: "event",
    date: "2026-06-01",
  },
  {
    id: "summer-1-recap",
    slug: "summer-1-100-tees",
    title: "SUMMER 1 RECAP: 100 TEES, ZERO ADS",
    excerpt: "Last summer we made 100 map tees and sold every single one. No website, no ads, no platform. Just the island and Instagram DMs. That's the proof of concept.",
    tag: "news",
    date: "2026-04-15",
  },
  {
    id: "why-1963",
    slug: "why-1963",
    title: "WHY 1963?",
    excerpt: "Before the marina. Before the package tourists. When Poros was just Poros. The photo on the tee is from that era. If you know, you know.",
    tag: "culture",
    date: "2026-04-10",
  },
  {
    id: "spots",
    slug: "spots-you-wont-find-on-google",
    title: "SPOTS YOU WON'T FIND ON GOOGLE MAPS",
    excerpt: "Love Bay. Kanali. The View. Russian Bay. Gerolimani. If you grew up here, you know every one. If you didn't — come find them.",
    tag: "culture",
    date: "2026-04-05",
  },
  {
    id: "protect-the-sea",
    slug: "protect-the-sea",
    title: "PROTECT THE SEA — IT'S NOT A SLOGAN",
    excerpt: "The back of the black tee isn't decoration. The waters around Poros are some of the cleanest in the Saronic. We want to keep it that way.",
    tag: "culture",
    date: "2026-03-28",
  },
  {
    id: "not-tourist-merch",
    slug: "this-is-not-tourist-merch",
    title: "THIS IS NOT TOURIST MERCH",
    excerpt: "No Santorini sunsets. No Mykonos windmills. This is Poros. Population 3,000. If you don't know, now you know.",
    tag: "manifesto",
    date: "2026-03-20",
  },
];